title: Utku Turk
description: Utku Turk's webpage
sourcecode: "https://github.com/utkuturk/utkuturk.github.io"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: ""                         # the base hostname & protocol for your site
baseurl: ""                     # the subpath of your site, e.g. /blog
# url: "localhost"              # for local testing
# baseurl: ""

author:
    name: Utku Türk
    scholar: wa7LG9gAAAAJ

# Build settings
markdown: kramdown
highlighter: rouge

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics:
    provider: false
    google:
        tracking_id: ''
    getclicky:
      site_id:
    mixpanel:
        token: ''
    piwik:
        baseURL: '' # Piwik installation address (without protocol)
        idsite: ''  # the id of the site on Piwik


# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
gitalk:
  client_id: 39da24c11eeca47d9313
  client_secret: f50623fc453e8bfc0acce506b9bd2e100c585d73
  owner: utkuturk
  repo: utkuturk.github.io
  admin: utkuturk


comments:
    provider: false
    disqus:
      short_name: utkuturk
    livefyre:
      site_id:
    intensedebate:
      account:
    facebook:
      appid:
      num_posts: 5
      width: 580
      colorscheme: light
